Chapter 2
asad5059/Intro-to-Java-Beginner-to-Advance pull request #3
Opened 2023-03-21 17:23 UTC by asad5059

Chapter 2 is done for now.

2023-03-26 10:45 UTC, laziestcoder commented on Chapter 2/README.md
this `README.md` file should be in `Intro-to-Java-Beginner-to-Advance/README.md` path. 
This `Chapter 2/README.md` should contain different data in it.

2023-03-26 10:46 UTC, laziestcoder requested changes
Please read the comment(s) and adopt necessary changes.

2023-03-29 18:05 UTC, asad5059 commented on Chapter 2/README.md
Necessary changes are made. Please review again bhaiya.

2023-03-29 18:16 UTC, laziestcoder requested changes
resolve the requested changes.

2023-03-29 18:16 UTC, laziestcoder commented on README.md
> -
You removed this file from the project. So after merging this file will be remove from the repository and you will not find it in the parent dir.  So, resolve it.

2023-03-30 21:46 UTC, laziestcoder approved these changes
LGTM

2023-03-30 21:46 UTC, merged